##### pandas

> pandas is a powerfull python library for manipulation and analysis of data

> its a open source library

> fast(built on top of numpy),flexible(different resource),prouctive library

#### install

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

In [4]:
pd.__version__

'2.2.3'

#### series - one dimensional array (data structure)with label

In [4]:
l1 = [1,2,3,4,5]
type(l1)

list

In [5]:
s=pd.Series(l1,index =["a","b","c","d","e"],name="my series")

In [6]:
s

a    1
b    2
c    3
d    4
e    5
Name: my series, dtype: int64

In [7]:
s['a']

np.int64(1)

In [8]:
type(s)

pandas.core.series.Series

In [9]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [10]:
s.values

array([1, 2, 3, 4, 5])

In [11]:
s.index[0]

'a'

### Note: index in series are immutable(can't change)

In [12]:
s.index[0]='z'

TypeError: Index does not support mutable operations

In [13]:
# changing the index of pandas series

s.rename(index={'b':'y'},inplace=True)

In [14]:
s

a    1
y    2
c    3
d    4
e    5
Name: my series, dtype: int64

### dataframe - its a 2 d array(just like tables)

In [3]:
import numpy as np

In [6]:
dict1= {'Name':['Virat','Rohit','dhoni','jadeja','bumrah','virat'],
        'age':[34,33,40,32,30,35],
        'marks':[85,90,75,80,70,np.nan],
        'role':['batsman','batsman','wicket keeper','all rounder','bowler','bowler']
        }
pd.DataFrame(dict1)

     Name  age  marks           role
0   Virat   34   85.0        batsman
1   Rohit   33   90.0        batsman
2   dhoni   40   75.0  wicket keeper
3  jadeja   32   80.0    all rounder
4  bumrah   30   70.0         bowler
5   virat   35    NaN         bowler

In [7]:
df=pd.DataFrame(dict1)

In [8]:
df

     Name  age  marks           role
0   Virat   34   85.0        batsman
1   Rohit   33   90.0        batsman
2   dhoni   40   75.0  wicket keeper
3  jadeja   32   80.0    all rounder
4  bumrah   30   70.0         bowler
5   virat   35    NaN         bowler

In [9]:
df.head

<bound method NDFrame.head of      Name  age  marks           role
0   Virat   34   85.0        batsman
1   Rohit   33   90.0        batsman
2   dhoni   40   75.0  wicket keeper
3  jadeja   32   80.0    all rounder
4  bumrah   30   70.0         bowler
5   virat   35    NaN         bowler>

In [10]:
df.tail(2)

     Name  age  marks    role
4  bumrah   30   70.0  bowler
5   virat   35    NaN  bowler

In [11]:
len(df)

6

In [12]:
df.count()

Name     6
age      6
marks    5
role     6
dtype: int64

In [13]:
df.columns

Index(['Name', 'age', 'marks', 'role'], dtype='object')

In [14]:
df['Name']

0     Virat
1     Rohit
2     dhoni
3    jadeja
4    bumrah
5     virat
Name: Name, dtype: object

In [15]:
type(df['Name'])

pandas.core.series.Series

In [16]:
df['Name'].value_counts()

Name
Virat     1
Rohit     1
dhoni     1
jadeja    1
bumrah    1
virat     1
Name: count, dtype: int64